"""init schema (uuid baseline)

Revision ID: f07744c1193c
Revises: 
Create Date: 2025-08-20 16:31:34.632969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg   # ← IMPORT CLAVE


# revision identifiers, used by Alembic.
revision: str = 'f07744c1193c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=True),
    sa.Column('sheet_id', sa.String(length=128), nullable=True),
    sa.Column('sheet_range', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes'))
    )
    op.create_index(op.f('ix_clientes_slug'), 'clientes', ['slug'], unique=True)
    op.create_table('catalog_active',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('pct_stock', sa.Float(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_json', pg.JSONB, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_catalog_active_cliente_id_clientes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_active')),
    sa.UniqueConstraint('cliente_id', name=op.f('uq_catalog_active_cliente_id'))
    )
    op.create_table('catalog_snapshots',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('origen', sa.String(length=32), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('filas_validas', sa.Integer(), nullable=True),
    sa.Column('errores_json', pg.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('blob_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_catalog_snapshots_cliente_id_clientes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_snapshots')),
    sa.UniqueConstraint('cliente_id', 'version', name='uq_snapshot_cliente_version')
    )
    op.create_index(op.f('ix_catalog_snapshots_cliente_id'), 'catalog_snapshots', ['cliente_id'], unique=False)
    op.create_index('ix_snapshot_cliente_created', 'catalog_snapshots', ['cliente_id', 'created_at'], unique=False)
    op.create_table(
        'client_contexts',
        sa.Column('id',        pg.UUID(as_uuid=True), nullable=False),
        sa.Column('cliente_id',pg.UUID(as_uuid=True), nullable=False),
        sa.Column('state_json',pg.JSONB, nullable=True),
        sa.Column('updated_at',sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_client_contexts')),
        sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_client_contexts_cliente_id_clientes')),
        sa.UniqueConstraint('cliente_id', name=op.f('uq_client_contexts_cliente_id'))
    )
    op.create_index(op.f('ix_client_contexts_cliente_id'), 'client_contexts', ['cliente_id'], unique=False)

    op.create_table('waba_accounts',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('waba_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number_id', sa.String(length=100), nullable=False),
    sa.Column('numero_e164', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('verify_token', sa.String(length=255), nullable=False),
    sa.Column('app_secret', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_waba_accounts_cliente_id_clientes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waba_accounts')),
    sa.UniqueConstraint('numero_e164', name=op.f('uq_waba_accounts_numero_e164'))
    )
    op.create_index(op.f('ix_waba_accounts_cliente_id'), 'waba_accounts', ['cliente_id'], unique=True)
    op.create_index(op.f('ix_waba_accounts_phone_number_id'), 'waba_accounts', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_waba_accounts_waba_id'), 'waba_accounts', ['waba_id'], unique=True)
    op.create_table('conversation_logs',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('waba_account_id', pg.UUID(as_uuid=True), nullable=True),
    sa.Column('user_msisdn', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('slots_json', pg.JSONB, nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('link_ctrs_json', pg.JSONB, nullable=True),
    sa.Column('handoff', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_conversation_logs_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['waba_account_id'], ['waba_accounts.id'], name=op.f('fk_conversation_logs_waba_account_id_waba_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_logs'))
    )
    op.create_index('ix_conversation_logs_cliente_created', 'conversation_logs', ['cliente_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_logs_cliente_id'), 'conversation_logs', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_user_msisdn'), 'conversation_logs', ['user_msisdn'], unique=False)
    op.create_index(op.f('ix_conversation_logs_waba_account_id'), 'conversation_logs', ['waba_account_id'], unique=False)
    op.create_table('convo_states',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('waba_account_id', pg.UUID(as_uuid=True), nullable=True),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('user_msisdn', sa.String(length=32), nullable=False),
    sa.Column('last_intent', sa.String(length=64), nullable=True),
    sa.Column('slots_json', pg.JSONB, nullable=True),
    sa.Column('context_json', pg.JSONB, nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_convo_states_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['waba_account_id'], ['waba_accounts.id'], name=op.f('fk_convo_states_waba_account_id_waba_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_convo_states')),
    sa.UniqueConstraint('waba_account_id', 'user_msisdn', name='uq_state_waba_user')
    )
    op.create_index(op.f('ix_convo_states_cliente_id'), 'convo_states', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_convo_states_user_msisdn'), 'convo_states', ['user_msisdn'], unique=False)
    op.create_index(op.f('ix_convo_states_waba_account_id'), 'convo_states', ['waba_account_id'], unique=False)
    op.create_table('ingest_logs',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('snapshot_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('origen', sa.String(length=32), nullable=False),
    sa.Column('urls_json', pg.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errores_json', pg.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('divergencias_json', pg.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filas_extraidas', sa.Integer(), nullable=True),
    sa.Column('pct_stock', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_ingest_logs_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['catalog_snapshots.id'], name=op.f('fk_ingest_logs_snapshot_id_catalog_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_logs')),
    sa.UniqueConstraint('cliente_id', 'run_id', name='uq_ingest_cliente_run')
    )
    op.create_index('ix_ingest_cliente_created', 'ingest_logs', ['cliente_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ingest_logs_cliente_id'), 'ingest_logs', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ingest_logs_run_id'), 'ingest_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_ingest_logs_snapshot_id'), 'ingest_logs', ['snapshot_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=True),
    sa.Column('waba_account_id', pg.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_usuarios_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['waba_account_id'], ['waba_accounts.id'], name=op.f('fk_usuarios_waba_account_id_waba_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_index(op.f('ix_usuarios_cliente_id'), 'usuarios', ['cliente_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=True),
    sa.Column('usuario_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_documentos_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_documentos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos'))
    )
    op.create_index(op.f('ix_documentos_cliente_id'), 'documentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_documentos_usuario_id'), 'documentos', ['usuario_id'], unique=False)
    op.create_table('membresias',
    sa.Column('id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('usuario_id', pg.UUID(as_uuid=True), nullable=False),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_membresias_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_membresias_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membresias'))
    )
    op.create_index(op.f('ix_membresias_cliente_id'), 'membresias', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_membresias_usuario_id'), 'membresias', ['usuario_id'], unique=False)
    # tabla corregida
    op.create_table(
        'user_contexts',
        sa.Column('id',         pg.UUID(as_uuid=True), nullable=False),
        sa.Column('usuario_id', pg.UUID(as_uuid=True), nullable=False),
        sa.Column('cliente_id', pg.UUID(as_uuid=True), nullable=False),  # ← era Integer
        sa.Column('msisdn',     sa.String(length=30), nullable=True),
        sa.Column('last_intent',sa.String(length=50), nullable=True),
        sa.Column('slots_json',   pg.JSONB, nullable=True),  # ← JSONB
        sa.Column('context_json', pg.JSONB, nullable=True),  # ← JSONB
        sa.Column('updated_at',   sa.DateTime(), server_default=sa.text('now()'), nullable=False),

        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_contexts')),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_user_contexts_usuario_id_usuarios')),
        sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'],  name=op.f('fk_user_contexts_cliente_id_clientes')),
        sa.UniqueConstraint('usuario_id', name=op.f('uq_user_contexts_usuario_id')),
    )
    op.create_index(op.f('ix_user_contexts_cliente_id'), 'user_contexts', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_contexts_cliente_id'), table_name='user_contexts')
    op.drop_table('user_contexts')
    op.drop_index(op.f('ix_membresias_usuario_id'), table_name='membresias')
    op.drop_index(op.f('ix_membresias_cliente_id'), table_name='membresias')
    op.drop_table('membresias')
    op.drop_index(op.f('ix_documentos_usuario_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_cliente_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_cliente_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_ingest_logs_snapshot_id'), table_name='ingest_logs')
    op.drop_index(op.f('ix_ingest_logs_run_id'), table_name='ingest_logs')
    op.drop_index(op.f('ix_ingest_logs_cliente_id'), table_name='ingest_logs')
    op.drop_index('ix_ingest_cliente_created', table_name='ingest_logs')
    op.drop_table('ingest_logs')
    op.drop_index(op.f('ix_convo_states_waba_account_id'), table_name='convo_states')
    op.drop_index(op.f('ix_convo_states_user_msisdn'), table_name='convo_states')
    op.drop_index(op.f('ix_convo_states_cliente_id'), table_name='convo_states')
    op.drop_table('convo_states')
    op.drop_index(op.f('ix_conversation_logs_waba_account_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_user_msisdn'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_cliente_id'), table_name='conversation_logs')
    op.drop_index('ix_conversation_logs_cliente_created', table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index(op.f('ix_waba_accounts_waba_id'), table_name='waba_accounts')
    op.drop_index(op.f('ix_waba_accounts_phone_number_id'), table_name='waba_accounts')
    op.drop_index(op.f('ix_waba_accounts_cliente_id'), table_name='waba_accounts')
    op.drop_table('waba_accounts')
    op.drop_table('client_contexts')
    op.drop_index('ix_snapshot_cliente_created', table_name='catalog_snapshots')
    op.drop_index(op.f('ix_catalog_snapshots_cliente_id'), table_name='catalog_snapshots')
    op.drop_table('catalog_snapshots')
    op.drop_table('catalog_active')
    op.drop_index(op.f('ix_clientes_slug'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
